import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the folder tree + _category_.json + sidebar_position frontmatter.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
